export const styles = {
  page: {
    minHeight: "100vh",
    background: "#f4f6f8",
    padding: "12px",
    fontFamily: "Arial, sans-serif",
    color: "#1f2937",
  },
  container: {
    maxWidth: 1100,
    margin: "0 auto",
  },
  header: {
    background: "#111827",
    color: "#ffffff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  title: {
    margin: 0,
    fontSize: 28,
  },
  subtitle: {
    marginTop: 8,
    marginBottom: 0,
    color: "#d1d5db",
  },
  card: {
    background: "#ffffff",
    border: "1px solid #d1d5db",
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    boxShadow: "0 2px 6px rgba(0,0,0,0.06)",
  },
  button: {
    padding: "12px 18px",
    borderRadius: 8,
    border: "1px solid #9ca3af",
    background: "#ffffff",
    cursor: "pointer",
    fontSize: 16,
  },
  primaryButton: {
    padding: "14px 20px",
    borderRadius: 8,
    border: "none",
    background: "#2563eb",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 16,
    width: "100%",
  },
  saveButton: {
    padding: "10px 14px",
    borderRadius: 8,
    border: "none",
    background: "#059669",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: "bold",
  },
  reportButton: {
    padding: "14px 20px",
    borderRadius: 8,
    border: "none",
    background: "#111827",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 10,
    width: "100%",
    maxWidth: 360,
  },
  disabledButton: {
    padding: "14px 20px",
    borderRadius: 8,
    border: "none",
    background: "#9ca3af",
    color: "#ffffff",
    cursor: "not-allowed",
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 20,
    width: "100%",
    maxWidth: 360,
  },
  tabButton: {
    padding: "12px 18px",
    borderRadius: 8,
    border: "1px solid #9ca3af",
    cursor: "pointer",
    fontSize: 16,
  },
  adminTabButton: {
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid #9ca3af",
    cursor: "pointer",
    fontSize: 15,
  },
  documentButton: {
    display: "block",
    padding: "14px 20px",
    borderRadius: 8,
    border: "none",
    background: "#059669",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 16,
    textDecoration: "none",
    textAlign: "center",
    width: "100%",
    boxSizing: "border-box",
  },
  input: {
    display: "block",
    marginBottom: 12,
    padding: 12,
    width: "100%",
    borderRadius: 8,
    border: "1px solid #9ca3af",
    fontSize: 16,
    boxSizing: "border-box",
  },
  smallInput: {
    padding: 8,
    width: "100%",
    borderRadius: 6,
    border: "1px solid #9ca3af",
    fontSize: 14,
    boxSizing: "border-box",
  },
  textarea: {
    display: "block",
    marginBottom: 12,
    padding: 12,
    width: "100%",
    minHeight: 120,
    borderRadius: 8,
    border: "1px solid #9ca3af",
    fontSize: 16,
    boxSizing: "border-box",
    fontFamily: "Arial, sans-serif",
  },
  select: {
    padding: 12,
    width: "100%",
    borderRadius: 8,
    border: "1px solid #9ca3af",
    fontSize: 16,
    marginTop: 8,
    marginBottom: 12,
    boxSizing: "border-box",
    background: "#ffffff",
  },
  smallSelect: {
    padding: 8,
    width: "100%",
    borderRadius: 6,
    border: "1px solid #9ca3af",
    fontSize: 14,
    boxSizing: "border-box",
    background: "#ffffff",
  },
  topicText: {
    whiteSpace: "pre-line",
    lineHeight: 1.6,
    fontSize: 17,
  },
  notice: {
    background: "#ecfdf5",
    border: "1px solid #10b981",
    color: "#065f46",
    padding: 12,
    borderRadius: 8,
    marginTop: 16,
  },
  warning: {
    background: "#fff7ed",
    border: "1px solid #f97316",
    color: "#9a3412",
    padding: 12,
    borderRadius: 8,
    marginTop: 16,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 12,
    marginTop: 16,
  },
  statBox: {
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: 14,
  },
  statNumber: {
    fontSize: 28,
    fontWeight: "bold",
    margin: 0,
  },
  statLabel: {
    margin: 0,
    color: "#4b5563",
  },
  tableWrap: {
    overflowX: "auto",
    marginTop: 16,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    background: "#ffffff",
  },
  th: {
    textAlign: "left",
    borderBottom: "2px solid #d1d5db",
    padding: 10,
    whiteSpace: "nowrap",
  },
  td: {
    borderBottom: "1px solid #e5e7eb",
    padding: 10,
    whiteSpace: "nowrap",
    verticalAlign: "top",
  },
  signedBadge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    background: "#dcfce7",
    color: "#166534",
    fontWeight: "bold",
  },
  pendingBadge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    background: "#fee2e2",
    color: "#991b1b",
    fontWeight: "bold",
  },
  roleBadge: {
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: 999,
    background: "#dbeafe",
    color: "#1e40af",
    fontWeight: "bold",
    marginLeft: 8,
  },
  languageRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 16,
    marginBottom: 16,
  },
  languageButton: {
    padding: "10px 16px",
    borderRadius: 8,
    border: "1px solid #9ca3af",
    cursor: "pointer",
    fontSize: 15,
  },
  inlineGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 12,
    alignItems: "end",
  },
  compactList: {
    display: "grid",
    gap: 10,
    marginTop: 16,
  },
  compactListItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: 12,
    background: "#f9fafb",
    flexWrap: "wrap",
  },
};
